### ISSUE TITLE
能否提供个试用地址？

### ISSUE THREAD

**Issue by BensonMax** [small99/AutoLine#1]

**Comment by small99** [comment]
请自己根据公众号中的安装部署教程安装使用

**Comment by BensonMax** [comment]
![image](https://user-images.githubusercontent.com/31434954/40034317-fd07f97c-582e-11e8-92a8-b6220bf0b93f.png)
![image](https://user-images.githubusercontent.com/31434954/40034334-0b2f1c60-582f-11e8-9961-44a33b0da4cc.png)
这个配置改哪里？没注释有点难

**Comment by small99** [comment]
不需要修改
