### ISSUE TITLE
安装依赖提示报错

### ISSUE THREAD

**Issue by wangcityboy** [small99/AutoLine#10]
.......
  Using cached https://files.pythonhosted.org/packages/35/06/bac4b9dad29f4c59bb0
c1d781c995940f4a39a964d5e0ea882e69c58495e/robotframework_seleniumlibrary-3.1.1-p
y2.py3-none-any.whl
Collecting robotframework-requests==0.4.7 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/6c/29/42b7f193595e71e4558
da5611ebd860d2cfbf3accebf9c3650e62829baee/robotframework-requests-0.4.7.tar.gz
Collecting robotframework-appiumlibrary==1.4.6 (from -r requirements.txt (line 2
1))
  Using cached https://files.pythonhosted.org/packages/eb/5a/1e27a66fbc7e711c272
0bb0b9a8c4fa5c4ca91171d3a245244e6efd01b3b/robotframework-appiumlibrary-1.4.6.tar
.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pytest-runner/: [SSL: CERTI
FICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720) -- Some packages ma
y not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_
FAILED] certificate verify failed (_ssl.c:720) -- Some packages may not be found
!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-1e388m2t\robotfra
mework-appiumlibrary\setup.py", line 59, in <module>
        include_package_data=True,
      File "c:\python\python35\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python\python35\lib\site-packages\setuptools\dist.py", line 315,
in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python\python35\lib\site-packages\setuptools\dist.py", line 361,
in fetch_build_eggs
        replace_conflicting=True,
      File "c:\python\python35\lib\site-packages\pkg_resources\__init__.py", lin
e 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python\python35\lib\site-packages\pkg_resources\__init__.py", lin
e 1122, in best_match
        return self.obtain(req, installer)
      File "c:\python\python35\lib\site-packages\pkg_resources\__init__.py", lin
e 1134, in obtain
        return installer(requirement)
      File "c:\python\python35\lib\site-packages\setuptools\dist.py", line 429,
in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python\python35\lib\site-packages\setuptools\command\easy_install
.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Re
quirement.parse('pytest-runner')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1
\AppData\Local\Temp\2\pip-install-1e388m2t\robotframework-appiumlibrary\

D:\python\AutoLine-master>pip -V
pip 10.0.1 from c:\python\python35\lib\site-packages\pip (python 3.5)

D:\python\AutoLine-master>python -V
Python 3.5.3

上面是我的信息，在win2008系统上
通过下面的方式：

1. 需要先安装好Python3，最好将pip升级到最新的版本（python）,先升级pip

> python -m pip install --upgrade pip

2. 安装AutoLine依赖包：

> pip install -r requirements.txt

**Comment by small99** [comment]
这个是你的网络太慢的问题，对于pip无法安装的包，请直接下对应的源码在本地进行安装即可

**Comment by wangcityboy** [comment]
谢谢，已经解决，亲自下载了一个：pytest_runner-4.2-py2.py3-none-any.whl
然后安装就可以了
