### ISSUE TITLE
 Data source does not exist.

### ISSUE THREAD

**Issue by LC6666** [small99/AutoLine#11]
执行用例，报这个错误是什么原因呢？
[ ERROR ] Parsing 'work/AutoLine-master/logs/1/2' failed: Data source does not exist.

**Comment by small99** [comment]
在autoline目录下运行python manage.py runserver  不然会出现路径错误的。。

**Comment by williamzh22** [comment]
我也遇到这个问题了，请问是怎么解决的？谢谢！

我就是在autoline目录下运行命令的：
Z:\Program Files\AutoLine-master>python manage.py runserver
