### ISSUE TITLE
创建接口测试用例，选择request库，报告中提示找不到seleniumlibrary库

### ISSUE THREAD

**Issue by wuwaer** [small99/AutoLine#13]
*** Settings ***
Library	Collections
Library	DateTime
Library	Dialogs
Library	OperatingSystem
Library	Process
Library	Screenshot
Library	String
Library	Telnet
Library	XML
Library	RequestsLibrary

Resource	resource.txt

Suite Setup  Screenshot.Set Screenshot Directory	/Users/wuwa/AutoLine/logs/3/3/images

Suite Teardown  SeleniumLibrary.Close all browsers

*** Test Cases ***

7-6 登录-获取产品列表.登录
	RequestsLibrary.Create Session	${interface}	${interfaceparams}		
7-7 登录-获取产品列表.获取产品列表
	RequestsLibrary.Get Request	${host}	${interface}	${interfaceparams}	
7-8 登录-获取产品列表.清空session
	RequestsLibrary.Delete All Sessions

**Comment by small99** [comment]
已解决
