### ISSUE TITLE
按照使用简明教程例子运行，Importing test library 'SeleniumLibrary' failed

### ISSUE THREAD

**Issue by YG-YS** [small99/AutoLine#16]
资源库都安装了没有问题
Error in file 'F:\PycharmProjects\AutoLine-master\logs\2\2\testcase.robot': Importing test library 'SeleniumLibrary' failed: ImportError: cannot import name 'EMPTY_NAMESPACE' Traceback (most recent call last):   File "C:\Program Files\Python\Python36\lib\site-packages\SeleniumLibrary\__init__.py", line 24, in <module>     from SeleniumLibrary.keywords import (AlertKeywords,   File "C:\Program Files\Python\Python36\lib\site-packages\SeleniumLibrary\keywords\__init__.py", line 17, in <module>     from .alert import AlertKeywords   File "C:\Program Files\Python\Python36\lib\site-packages\SeleniumLibrary\keywords\alert.py", line 18, in <module>     from selenium.webdriver.support import expected_conditions as EC   File "C:\Program Files\Python\Python36\lib\site-packages\selenium\webdriver\__init__.py", line 18, in <module>     from .firefox.webdriver import WebDriver as Firefox  # noqa   File "C:\Program Files\Python\Python36\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 39, in <module>     from .firefox_profile import FirefoxProfile   File "C:\Program Files\Python\Python36\lib\site-packages\selenium\webdriver\firefox\firefox_profile.py", line 35, in <module>     from xml.dom import minidom   File "C:\Program Files\Python\Python36\lib\xml\dom\minidom.py", line 21, in <module>     from xml.dom import EMPTY_NAMESPACE, EMPTY_PREFIX, XMLNS_NAMESPACE, domreg
--

**Comment by small99** [comment]
你这是没下载geckdirver.exe？

**Comment by YG-YS** [comment]
工程bin目录下是有geckdirver.exe的；
完全照搬的例子，browser设的是Chorme

**Comment by small99** [comment]
![image](https://user-images.githubusercontent.com/10411707/40897982-fc1b9344-67f0-11e8-87ef-6c74c1db08f8.png)
你加入到这个讨论组里，把更详细的细节都贴上去

**Comment by YG-YS** [comment]
详细报告和testcase.robot



![1](https://user-images.githubusercontent.com/39614871/40900484-65b41134-67fe-11e8-9688-6d215175a258.PNG)
