### ISSUE TITLE
创建项目失败

### ISSUE THREAD

**Issue by NextOneWxf** [small99/AutoLine#2]
![image](https://user-images.githubusercontent.com/4550421/40050141-2ea3b112-5869-11e8-85fa-2dc0ea7a08a5.png)

**Comment by NextOneWxf** [comment]
![image](https://user-images.githubusercontent.com/4550421/40050334-b599915a-5869-11e8-976d-f1786aa24158.png)

**Comment by NextOneWxf** [comment]
![image](https://user-images.githubusercontent.com/4550421/40050546-5c61211a-586a-11e8-8578-7a9120dfe156.png)
![image](https://user-images.githubusercontent.com/4550421/40050559-64bad23e-586a-11e8-96b1-7ac39b271a75.png)

**Comment by small99** [comment]
创建项目前，先创建产品，必须选择了产品才能创建项目，否则会报异常，这里没做异常处理的

**Comment by NextOneWxf** [comment]
请看后面那张图 就是在创建产品

**Comment by small99** [comment]
你的代码是最新的吗？我这边试了，是没出现问题的，看你的图，是因为编码问题，得知道你的环境才好定位问题，加我微信：liyimin1912  拉你进微信群，有问题在群里提 会更方便些

**Comment by NextOneWxf** [comment]
确定最新的 我给你看下gitlog 
![image](https://user-images.githubusercontent.com/4550421/40051161-5d5d1c20-586c-11e8-8354-c8f260e83ca2.png)
