### ISSUE TITLE
创建产品，产品名只有英文可以，且创建成功后数据库可见，但是web网页端还是无显示

### ISSUE THREAD

**Issue by NextOneWxf** [small99/AutoLine#3]
![image](https://user-images.githubusercontent.com/4550421/40050980-b7e6e316-586b-11e8-9bd9-848b07b86c47.png)
![image](https://user-images.githubusercontent.com/4550421/40050998-c5c368e2-586b-11e8-8670-2ab319229db6.png)
但是首页可见
![image](https://user-images.githubusercontent.com/4550421/40051071-ff5e5440-586b-11e8-9ead-fc87e593d29d.png)

**Comment by small99** [comment]
你的数据库创建时  是utf-8编码吗? 感觉你的是默认latin编码

**Comment by NextOneWxf** [comment]
![image](https://user-images.githubusercontent.com/4550421/40113233-5665fb74-593b-11e8-8c5e-721d682afb45.png)
